#!/usr/bin/env bash
# Bash script that uses ssh to connect to a server
# private key ~/.ssh/school; user ubuntu; host IP given as 54.235.48.253
ssh -i /alu-system_engineering-devops/ssh/school ubuntu@54.235.48.253
