#!/usr/bin/env bash
# Bash script that uses ssh to connect to a server
# private key ~/.ssh/school; user ubuntu; host IP given as
ssh -i /alu-system_engineering-devops/ssh/school ubuntu@54.145.59.195
