#!/usr/bin/env bash

# Set the filename for the private key
private_key="school"

# Set the number of bits for the key
bits=4096

# Set the passphrase for the key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b $bits -f "$private_key" -N "$passphrase"

echo "RSA key pair generated successfully."
echo "Private key: $private_key"
echo "Passphrase: $passphrase"

